Add missing target dependency on rcpputils (osrf#90)
Fixes a build issue with newer versions of ROS Rolling:

    fatal error: rcpputils/scope_exit.hpp: No such file or directory

Signed-off-by: Jacob Perron <jacob@openrobotics.org>